

trigger:
- master

variables:
  pomDir: 'Backend/project-gladiator/gladiator'

pool:
  vmImage: ubuntu-latest

steps:
- script: pwd
  displayName: 'check dir'
- script: ls -la
  displayName: 'check files'

- script: mvn package
  displayName: 'mvn package'
  workingDirectory: $(pomDir)

